import type { SiteLocale } from "@/lib/site-i18n";

export const EN = {
  dir: "ltr" as "ltr" | "rtl",
  lang: "en" as "en" | "fr" | "ar",
  meta: {
    defaultTitle: "GreatImmob — Stays in Agadir, Marrakech & Essaouira",
    description:
      "Book short stays in Agadir, Marrakech and Essaouira. Request dates, host confirmation, check-in with ID. Hosted on the ground by Hamza.",
    stays: "Stays",
    staysDesc: "Short stays in Agadir, Marrakech and Essaouira. Request to book with Hamza.",
    stay: "The apartment",
    how: "How it works",
    howDesc: "Search, request to book, host confirmation, WhatsApp payment, then check-in with ID.",
    rules: "Guest rules & Moroccan law",
    rulesDesc: "How short stays are hosted in Morocco: law 80-14, guest identity, house rules, and stay tax.",
    help: "Help",
    helpDesc: "WhatsApp Hamza for dates, check-in, or a stay in Agadir, Marrakech or Essaouira.",
    destination: (city: string) => `${city} stays`,
    destinationDesc: (city: string, tagline: string) => `Short stays in ${city}, Morocco. ${tagline}`,
  },
  nav: {
    stays: "Stays",
    destinations: "Destinations",
    howItWorks: "How it works",
    guestRules: "Guest rules",
    help: "Help",
    logIn: "Log in",
    signUp: "Sign up",
    menu: "Menu",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    language: "Language",
  },
  footer: {
    blurb:
      "Short stays in Agadir, Marrakech and Essaouira. Request to book, host confirmation, then check-in — the same rhythm as Airbnb or Booking, with Hamza on WhatsApp.",
    book: "Book",
    stay: "Stay",
    allStays: "All stays",
    superhost: (host: string) => `${host} · Superhost · Morocco`,
  },
  search: {
    where: "Where",
    checkIn: "Check-in",
    checkout: "Checkout",
    guests: "Guests",
    who: "Who",
    addGuests: "Add guests",
    guest1: "1 guest",
    guest2: "2 guests",
    adults: "Adults",
    adultsHint: "Ages 13+",
    children: "Children",
    childrenHint: "Ages 2–12",
    pets: "Pets",
    petsHint: "Bringing a service animal?",
    petsNotAllowed: "This home does not allow pets.",
    maxPeople: "This apartment sleeps 2.",
    peopleSummary: (n: number) => (n === 1 ? "1 guest" : `${n} guests`),
    petsSummary: (n: number) => (n === 1 ? "1 pet" : `${n} pets`),
    search: "Search",
  },
  city: {
    agadir: {
      name: "Agadir",
      region: "Atlantic coast",
      tagline: "Beach city, winter sun, the road to Taghazout.",
      blurb:
        "Agadir is the live city on this site today: an apartment you can request to book, with Hamza on the ground for keys, WhatsApp, and check-in.",
      heroAlt: "Agadir bay and beach, Morocco",
      cardAlt: "Agadir beach with the Oufella hill",
    },
    marrakech: {
      name: "Marrakech",
      region: "Medina & Palmeraie",
      tagline: "Riads, courtyards, and nights in the red city.",
      blurb:
        "Marrakech homes will appear here when they are live — same request-to-book flow, same host, no invented listings.",
      heroAlt: "Jemaa el-Fnaa square in Marrakech at dusk",
      cardAlt: "Koutoubia Mosque at sunset, Marrakech",
    },
    essaouira: {
      name: "Essaouira",
      region: "Atlantic medina",
      tagline: "Ramparts, wind, and the working port.",
      blurb:
        "Essaouira is on the map for the same collection. When a stay is ready, it will sit next to Agadir — not before.",
      heroAlt: "White and blue houses behind the ramparts of Essaouira",
      cardAlt: "Blue fishing boats in the port of Essaouira",
    },
  },
  home: {
    citiesLine: "Agadir · Marrakech · Essaouira",
    title: "Book a stay in Morocco.",
    titleAccent: " Direct with the host.",
    lead: "Apartments you request like Airbnb, confirm like a Superhost, and check into with ID — not a brochure about a company.",
    searchHint: "Request to book · Hamza confirms · Check-in with passport or CIN",
    destinationsEyebrow: "Destinations",
    destinationsTitle: "Where you can stay",
    homesAvailable: "Homes available",
    openingSoon: "Opening soon",
    availableNow: "Available now",
    placesToBook: "Places to book",
    allStays: "All stays",
    howEyebrow: "How booking works",
    howTitle: "Same idea as the big platforms. Smaller, on the ground.",
    fullPath: "Full booking path →",
    airbnbRating: "Airbnb rating",
    guestReviews: "Guest reviews",
    notInstant: "Not instant book",
    request: "Request",
    lawEyebrow: "Guest rules · Morocco",
    lawTitle: "Short stays here follow Moroccan tourist rules.",
    lawLead:
      "Law 80-14, guest identity at check-in, house rules in French, stay tax if the commune applies it. The same standard a classified tourist home owes a guest — and the state.",
    readRules: "Read guest rules",
    lawPoints: [
      "A few nights in a furnished home is a tourist stay, not a residential lease.",
      "Passport or CIN at check-in — hosts must know who is in the home.",
      "No parties, no undeclared extra guests. Unmarried Moroccan couples are not accommodated.",
    ],
    faqEyebrow: "Questions",
    faqTitle: "Before you request",
    whatsappTitle: "Need a night that is not online yet?",
    whatsappLead: "Dates, city, two guests — Hamza answers on WhatsApp.",
    messageHamza: "Message Hamza",
    waMessage: "Hello Hamza, I want to book a stay.",
    steps: [
      { n: "01", t: "Search a city", d: "Agadir is live. Marrakech and Essaouira open as homes go live — never as fake cards." },
      { n: "02", t: "Request to book", d: "Send dates from your account. Hamza confirms so this calendar and Airbnb never overlap." },
      { n: "03", t: "Pay after confirmation", d: "No card on this site yet. The amount comes on WhatsApp once the stay is yours." },
      { n: "04", t: "Check in", d: "A private link: identity, house rules, handwritten signature — the same file a serious tourist stay needs in Morocco." },
    ],
    faqs: [
      {
        q: "Is this Instant Book?",
        a: "No. Every stay is a request. That is how we keep one apartment from being sold on Airbnb and here on the same night.",
      },
      {
        q: "Why do you ask for ID?",
        a: "Moroccan tourist stays keep a guest register. Check-in is the legal file, not a marketing form.",
      },
      {
        q: "Can I book Marrakech or Essaouira today?",
        a: "Those cities are on the map. Listings appear when a home is actually ready. Agadir is the city you can request now.",
      },
    ],
  },
  stays: {
    eyebrow: "Search",
    inCity: (city: string) => `Stays in ${city}`,
    inMorocco: "Stays in Morocco",
    lead: "Request dates. Hamza confirms. Agadir is live; Marrakech and Essaouira join when a home is actually ready.",
    all: "All",
    emptyTitle: (city: string) => `No live home in ${city} yet`,
    emptyLead: "We do not invent apartments. Tell Hamza your dates — or book the Agadir stay that is open now.",
    seeAgadir: "See Agadir",
    waLooking: (city: string) => `Hello Hamza, I am looking for a stay in ${city}.`,
  },
  stay: {
    reviews: (n: number) => `${n} reviews`,
    hostedBy: (host: string, role: string) => `Hosted by ${host} · ${role}`,
    facts: (guests: number, bedrooms: number, beds: number, baths: number) =>
      `${guests} guests · ${bedrooms} bedroom · ${beds} bed · ${baths} baths`,
    houseRules: "House rules",
    houseRulesLead: "The same rules as the stay contract. French original.",
    whyId: "Why we ask for ID, and Moroccan short-stay law",
    alsoListed: "Also listed on",
    calendars: ". Hamza confirms .com requests so the two calendars never overlap.",
    whatsapp: (host: string, phone: string) => `WhatsApp ${host} · ${phone}`,
    title: "Luxury 1BR Apartment | Fiber WiFi | Quiet & Elegant",
    subtitle: "Entire rental unit · Hay Mohammadi, Agadir",
    about:
      "A quiet 1-bedroom apartment in Hay Mohammadi, Agadir — the same home Hamza hosts on Airbnb as a Superhost. Fibre Wi-Fi, one bed, 1.5 baths. Two guests.",
    badges: ["Guest favourite", "Top 10% of homes"],
    amenities: ["Fibre Wi-Fi", "Entire apartment", "1 bedroom", "1 bed", "1.5 baths", "Quiet building"],
    headline: "Quiet 1-bedroom in Hay Mohammadi",
  },
    dest: {
    openingTitle: (city: string) => `Homes in ${city} are being prepared`,
    openingLead: "No invented listings. When a stay is live, it will appear here. Agadir is bookable today.",
    bookAgadir: "Book Agadir",
    whatsappHamza: "WhatsApp Hamza",
    waCity: (city: string) => `Hello Hamza, I am looking for a stay in ${city}.`,
  },
  how: {
    eyebrow: "Booking",
    title: "How you book a stay",
    lead: (phone: string) =>
      `The path is the one you already know from Airbnb or Booking: search, dates, request, confirmation — then a proper Moroccan check-in, with Hamza on ${phone}.`,
    searchStays: "Search stays",
    guestRules: "Guest rules",
    steps: [
      {
        n: "01",
        t: "Choose a city and dates",
        d: "Search Agadir, Marrakech or Essaouira. Only live homes appear. Today that is the 1-bedroom in Hay Mohammadi, Agadir.",
      },
      {
        n: "02",
        t: "Create a guest account",
        d: "A booking request needs a name and email — the same people who will check in.",
      },
      {
        n: "03",
        t: "Request to book",
        d: "Not Instant Book. Hamza confirms so this calendar and Airbnb cannot sell the same night twice.",
      },
      {
        n: "04",
        t: "Pay on WhatsApp",
        d: "After confirmation, Hamza sends the amount. No card on this site yet.",
      },
      {
        n: "05",
        t: "Check in on your link",
        d: "Passport or CIN, house rules, handwritten signature. That file is how tourist stays are identified in Morocco.",
      },
    ],
  },
  rules: {
    eyebrow: "For guests",
    title: "Guest rules & Moroccan law",
    disclaimer:
      "This page explains how we host short stays in Morocco. It is not a lawyer’s opinion and does not replace the stay contract. The French house rules you sign at check-in are the rules of the home.",
    houseRulesTitle: "House rules (French original)",
    houseRulesLead: "These are the rules you sign at check-in.",
    sourcesTitle: "The texts we follow",
    searchStays: "Search stays",
    howBooking: "How booking works",
    sections: [
      {
        id: "what-you-are-booking",
        title: "What you are booking",
        body: [
          "A stay here is a short tourist stay in a furnished home — nights, not a year, not a principal residence. In Moroccan law that sits with tourist accommodation (law 80-14), not with the residential lease (law 67-12).",
          "Platforms (Airbnb, Booking, Vrbo, or this site) do not replace the host’s duties. The host is the person who confirms the stay, identifies guests, and hands over the keys. Here that person is Hamza.",
          "We do not use Instant Book. A request is confirmed only when the calendar is free here and on Airbnb, so the same apartment cannot be sold twice.",
        ],
      },
      {
        id: "why-id",
        title: "Why we ask for your identity",
        body: [
          "Tourist hosts in Morocco keep a guest register and declare travellers to the local authorities (arrival forms / police fiche). That is why check-in asks for a passport or CIN, and a signature, before arrival is complete.",
          "The file is not a marketing form. It is how a serious short stay is run: who is in the home, for which nights, under which house rules.",
          "Names on the booking must match the people who sleep in the apartment. Extra unannounced guests are refused.",
        ],
      },
      {
        id: "tax",
        title: "Tourist tax",
        body: [
          "Communes may levy a stay tax (taxe de séjour) per person per night on tourist lodging, including furnished apartments let to travellers. The rate is local — Agadir, Marrakech, and Essaouira each set their own.",
          "If a tax applies to your stay, Hamza states it with the confirmation, in dirhams. This site does not invent a number on your behalf.",
          "Airbnb and Booking do not always collect Moroccan stay tax for the host. Direct booking here does not hide that duty; it keeps it on the confirmation you actually receive.",
        ],
      },
      {
        id: "house-rules",
        title: "House rules that are not optional",
        body: [
          "The apartment is a short-stay home, not a party venue, film set, or shop. Gatherings, undeclared commercial shoots, indoor smoking, and pets are refused — as written in the French rules you sign.",
          "Unmarried Moroccan couples are not accommodated in this home. That is a house rule, applied at booking and at the door, in line with how this stay is run in Morocco.",
          "Respect for neighbours is part of the stay. Complaints from the building can end the stay without a refund of remaining nights.",
        ],
      },
      {
        id: "cities",
        title: "Agadir, Marrakech, Essaouira",
        body: [
          "The same guest duties follow the stay, not the logo of a platform: identity, quiet building, confirmed dates, payment as agreed on WhatsApp after confirmation.",
          "Today the live, bookable home is in Agadir. Marrakech and Essaouira are cities we host for — listings appear when a home is actually ready.",
        ],
      },
    ],
    sources: [
      {
        name: "Law no. 80-14 on tourist establishments and other forms of tourist accommodation",
        note: "Dahir no. 1-15-108 of 18 August 2015. The frame for hotels, riads, guesthouses, and furnished tourist rentals.",
      },
      {
        name: "Decree no. 2-23-441",
        note: "Published 2023. Application rules for tourist accommodation, including forms that used to sit in a grey zone on booking platforms.",
      },
      {
        name: "Law no. 47-06, as amended (notably by law no. 07-20)",
        note: "Local taxation, including the tourist stay tax (taxe de séjour) set by each commune.",
      },
      {
        name: "Law no. 67-12 on the lease of residential premises",
        note: "The ordinary home-rental law. A stay of a few nights is not that contract.",
      },
    ],
  },
  help: {
    eyebrow: "Help",
    title: "Message the host",
    lead: "Dates, arrival, check-in, Marrakech or Essaouira when a home is not online yet — one WhatsApp, Hamza.",
    whatsapp: "WhatsApp",
    cities: "Hamza · Agadir, Marrakech, Essaouira",
    openWa: "Open WhatsApp",
    before: "Before you write",
    bullets: [
      "Request to book on the stay page if Agadir dates are what you need.",
      "Check-in is a private link after confirmation — ID and signature.",
      "Exact door codes are sent after booking, not published here.",
    ],
    openStay: "Open the Agadir stay →",
    waMessage: "Hello Hamza, I have a question about a stay.",
  },
  auth: {
    eyebrow: "Guest",
    logIn: "Log in",
    wrong: "Wrong email or password.",
    email: "Email",
    password: "Password",
    continue: "Continue",
    newHere: "New here?",
    createAccount: "Create an account",
    createTitle: "Create account",
    fullName: "Full name",
    phone: "Phone / WhatsApp",
    passwordHint: "Password (8+)",
    haveOne: "Already have one?",
  },
  account: {
    eyebrow: "Your stay",
    hello: (name: string) => `Hello, ${name}`,
    requested: "Request sent. Hamza will confirm on WhatsApp so the Airbnb calendar stays clear.",
    empty: "No requests yet.",
    seeApartment: "See the apartment",
    line: (nights: number, guests: number, total: number, status: string) =>
      `${nights} nights · ${guests} guests · ${total} MAD · ${status}`,
    status: {
      pending: "Requested",
      confirmed: "Confirmed",
      declined: "Declined",
      cancelled: "Cancelled",
    },
    openCheckin: "Open check-in",
    logOut: "Log out",
  },
  booking: {
    perNight: "/ night",
    seasonal: "Seasonal · 400–550 MAD. Cleaning is billed to the owner, not added here.",
    nights: (n: number) => (n === 1 ? "1 night" : `${n} nights`),
    total: "Total",
    conflict: "Those nights overlap a stay already on the calendar.",
    unavailable: "Those dates are not available.",
    failed: "Booking failed.",
    sending: "Sending…",
    request: "Request to book",
    logInToRequest: "Log in to request",
    notInstant: "Not instant. Hamza confirms so this calendar and Airbnb never clash. Payment on WhatsApp after confirmation — no card on this site yet.",
  },
  card: {
    availableNow: "Available now",
    facts: (guests: number, bedrooms: number, beds: number, baths: number) =>
      `${guests} guests · ${bedrooms} bedroom · ${beds} bed · ${baths} baths`,
    fromNight: (amount: number) => `From ${amount} MAD / night`,
    reviews: (rating: string, n: number) => `★ ${rating} · ${n} reviews`,
  },
};

export const FR: typeof EN = {
  dir: "ltr",
  lang: "fr",
  meta: {
    defaultTitle: "GreatImmob — Séjours à Agadir, Marrakech et Essaouira",
    description:
      "Réservez un court séjour à Agadir, Marrakech ou Essaouira. Demande de dates, confirmation de l’hôte, check-in avec pièce d’identité. Hamza sur place.",
    stays: "Séjours",
    staysDesc: "Courts séjours à Agadir, Marrakech et Essaouira. Demande de réservation auprès de Hamza.",
    stay: "L’appartement",
    how: "Comment ça marche",
    howDesc: "Recherche, demande, confirmation de l’hôte, paiement WhatsApp, puis check-in avec pièce d’identité.",
    rules: "Règles voyageurs et droit marocain",
    rulesDesc: "Comment nous accueillons un court séjour au Maroc : loi 80-14, identité, règlement intérieur, taxe de séjour.",
    help: "Aide",
    helpDesc: "WhatsApp Hamza pour les dates, le check-in, ou un séjour à Agadir, Marrakech ou Essaouira.",
    destination: (city: string) => `Séjours à ${city}`,
    destinationDesc: (city: string, tagline: string) => `Courts séjours à ${city}, Maroc. ${tagline}`,
  },
  nav: {
    stays: "Séjours",
    destinations: "Destinations",
    howItWorks: "Comment ça marche",
    guestRules: "Règles voyageurs",
    help: "Aide",
    logIn: "Connexion",
    signUp: "Inscription",
    menu: "Menu",
    openMenu: "Ouvrir le menu",
    closeMenu: "Fermer le menu",
    language: "Langue",
  },
  footer: {
    blurb:
      "Courts séjours à Agadir, Marrakech et Essaouira. Demande de réservation, confirmation de l’hôte, puis check-in — le même rythme qu’Airbnb ou Booking, avec Hamza sur WhatsApp.",
    book: "Réserver",
    stay: "Séjour",
    allStays: "Tous les séjours",
    superhost: (host: string) => `${host} · Superhôte · Maroc`,
  },
  search: {
    where: "Où",
    checkIn: "Arrivée",
    checkout: "Départ",
    guests: "Voyageurs",
    who: "Qui",
    addGuests: "Ajouter des voyageurs",
    guest1: "1 voyageur",
    guest2: "2 voyageurs",
    adults: "Adultes",
    adultsHint: "13 ans et plus",
    children: "Enfants",
    childrenHint: "2 à 12 ans",
    pets: "Animaux",
    petsHint: "Vous voyagez avec un animal ?",
    petsNotAllowed: "Cet appartement n’accepte pas les animaux.",
    maxPeople: "Cet appartement accueille 2 personnes.",
    peopleSummary: (n: number) => (n === 1 ? "1 voyageur" : `${n} voyageurs`),
    petsSummary: (n: number) => (n === 1 ? "1 animal" : `${n} animaux`),
    search: "Rechercher",
  },
  city: {
    agadir: {
      name: "Agadir",
      region: "Côte atlantique",
      tagline: "Ville de plage, soleil d’hiver, la route vers Taghazout.",
      blurb:
        "Agadir est la ville ouverte sur ce site aujourd’hui : un appartement à demander, avec Hamza sur place pour les clés, WhatsApp et le check-in.",
      heroAlt: "Baie et plage d’Agadir, Maroc",
      cardAlt: "Plage d’Agadir et colline d’Oufella",
    },
    marrakech: {
      name: "Marrakech",
      region: "Médina et Palmeraie",
      tagline: "Riads, patios, et les nuits de la ville ocre.",
      blurb:
        "Les logements de Marrakech apparaîtront ici lorsqu’ils seront réellement ouverts — même demande de réservation, même hôte, aucun logement inventé.",
      heroAlt: "Place Jemaa el-Fna à Marrakech au crépuscule",
      cardAlt: "Mosquée de la Koutoubia au coucher du soleil, Marrakech",
    },
    essaouira: {
      name: "Essaouira",
      region: "Médina atlantique",
      tagline: "Remparts, vent, et le port qui travaille.",
      blurb:
        "Essaouira est sur la carte de la même collection. Quand un séjour sera prêt, il s’affichera à côté d’Agadir — pas avant.",
      heroAlt: "Maisons blanches et bleues derrière les remparts d’Essaouira",
      cardAlt: "Bateaux de pêche bleus au port d’Essaouira",
    },
  },
  home: {
    citiesLine: "Agadir · Marrakech · Essaouira",
    title: "Réservez un séjour au Maroc.",
    titleAccent: " En direct avec l’hôte.",
    lead: "Des appartements que vous demandez comme sur Airbnb, confirmez comme chez un Superhôte, et où vous faites le check-in avec une pièce d’identité — pas une plaquette d’entreprise.",
    searchHint: "Demande de réservation · Hamza confirme · Check-in passeport ou CIN",
    destinationsEyebrow: "Destinations",
    destinationsTitle: "Où séjourner",
    homesAvailable: "Logements disponibles",
    openingSoon: "Bientôt",
    availableNow: "Disponible maintenant",
    placesToBook: "À réserver",
    allStays: "Tous les séjours",
    howEyebrow: "La réservation",
    howTitle: "La même idée que les grandes plateformes. Plus petit, sur place.",
    fullPath: "Le parcours complet →",
    airbnbRating: "Note Airbnb",
    guestReviews: "Avis voyageurs",
    notInstant: "Pas de réservation instantanée",
    request: "Demande",
    lawEyebrow: "Règles voyageurs · Maroc",
    lawTitle: "Ici, le court séjour suit les règles touristiques marocaines.",
    lawLead:
      "Loi 80-14, identité au check-in, règlement en français, taxe de séjour si la commune l’applique. Le même standard qu’un hébergement touristique classé doit à l’hôte — et à l’État.",
    readRules: "Lire les règles voyageurs",
    lawPoints: [
      "Quelques nuits dans un logement meublé, c’est un séjour touristique, pas un bail d’habitation.",
      "Passeport ou CIN au check-in — l’hôte doit savoir qui est dans le logement.",
      "Pas de fêtes, pas de voyageurs non déclarés. Les couples marocains non mariés ne sont pas accueillis.",
    ],
    faqEyebrow: "Questions",
    faqTitle: "Avant de demander",
    whatsappTitle: "Une nuit qui n’est pas encore en ligne ?",
    whatsappLead: "Dates, ville, deux voyageurs — Hamza répond sur WhatsApp.",
    messageHamza: "Écrire à Hamza",
    waMessage: "Bonjour Hamza, je souhaite réserver un séjour.",
    steps: [
      { n: "01", t: "Chercher une ville", d: "Agadir est ouvert. Marrakech et Essaouira s’ajoutent quand un logement est réellement prêt — jamais de fausses cartes." },
      { n: "02", t: "Demander à réserver", d: "Envoyez les dates depuis votre compte. Hamza confirme pour que ce calendrier et Airbnb ne se recoupent jamais." },
      { n: "03", t: "Payer après confirmation", d: "Pas de carte sur ce site pour l’instant. Le montant arrive sur WhatsApp une fois le séjour à vous." },
      { n: "04", t: "Check-in", d: "Un lien privé : identité, règlement, signature manuscrite — le dossier qu’un séjour touristique sérieux doit tenir au Maroc." },
    ],
    faqs: [
      {
        q: "Est-ce une réservation instantanée ?",
        a: "Non. Chaque séjour est une demande. C’est ainsi qu’un même appartement ne se vend pas sur Airbnb et ici la même nuit.",
      },
      {
        q: "Pourquoi une pièce d’identité ?",
        a: "Les séjours touristiques au Maroc tiennent un registre des voyageurs. Le check-in est le dossier légal, pas un formulaire marketing.",
      },
      {
        q: "Puis-je réserver Marrakech ou Essaouira aujourd’hui ?",
        a: "Ces villes sont sur la carte. Les annonces apparaissent quand un logement est réellement prêt. Agadir est la ville que vous pouvez demander maintenant.",
      },
    ],
  },
  stays: {
    eyebrow: "Recherche",
    inCity: (city: string) => `Séjours à ${city}`,
    inMorocco: "Séjours au Maroc",
    lead: "Demandez des dates. Hamza confirme. Agadir est ouvert ; Marrakech et Essaouira s’ajoutent quand un logement est réellement prêt.",
    all: "Tous",
    emptyTitle: (city: string) => `Pas encore de logement ouvert à ${city}`,
    emptyLead: "Nous n’inventons pas d’appartements. Donnez vos dates à Hamza — ou réservez le séjour d’Agadir déjà ouvert.",
    seeAgadir: "Voir Agadir",
    waLooking: (city: string) => `Bonjour Hamza, je cherche un séjour à ${city}.`,
  },
  stay: {
    reviews: (n: number) => `${n} avis`,
    hostedBy: (host: string, role: string) => `Hôte : ${host} · ${role}`,
    facts: (guests: number, bedrooms: number, beds: number, baths: number) =>
      `${guests} voyageurs · ${bedrooms} chambre · ${beds} lit · ${baths} salles de bain`,
    houseRules: "Règlement intérieur",
    houseRulesLead: "Les mêmes règles que le contrat de séjour. Version originale en français.",
    whyId: "Pourquoi une pièce d’identité, et le droit du court séjour au Maroc",
    alsoListed: "Aussi sur",
    calendars: ". Hamza confirme les demandes .com pour que les deux calendriers ne se recoupent jamais.",
    whatsapp: (host: string, phone: string) => `WhatsApp ${host} · ${phone}`,
    title: "Appartement 1 chambre | Fibre Wi-Fi | Calme et élégant",
    subtitle: "Logement entier · Hay Mohammadi, Agadir",
    about:
      "Un appartement calme d’une chambre à Hay Mohammadi, Agadir — le même logement que Hamza accueille sur Airbnb en Superhôte. Fibre Wi-Fi, un lit, 1,5 salle de bain. Deux voyageurs.",
    badges: ["Coup de cœur voyageurs", "Top 10 % des logements"],
    amenities: ["Fibre Wi-Fi", "Appartement entier", "1 chambre", "1 lit", "1,5 salle de bain", "Immeuble calme"],
    headline: "1 chambre calme à Hay Mohammadi",
  },
  dest: {
    openingTitle: (city: string) => `Les logements à ${city} se préparent`,
    openingLead: "Aucun logement inventé. Quand un séjour sera ouvert, il apparaîtra ici. Agadir se réserve déjà.",
    bookAgadir: "Réserver Agadir",
    whatsappHamza: "WhatsApp Hamza",
    waCity: (city: string) => `Bonjour Hamza, je cherche un séjour à ${city}.`,
  },
  how: {
    eyebrow: "Réservation",
    title: "Comment réserver un séjour",
    lead: (phone: string) =>
      `Le parcours est celui que vous connaissez déjà sur Airbnb ou Booking : recherche, dates, demande, confirmation — puis un vrai check-in marocain, avec Hamza au ${phone}.`,
    searchStays: "Chercher un séjour",
    guestRules: "Règles voyageurs",
    steps: [
      {
        n: "01",
        t: "Choisir une ville et des dates",
        d: "Cherchez Agadir, Marrakech ou Essaouira. Seuls les logements ouverts apparaissent. Aujourd’hui, c’est le 1 chambre de Hay Mohammadi, à Agadir.",
      },
      {
        n: "02",
        t: "Créer un compte voyageur",
        d: "Une demande de réservation a besoin d’un nom et d’un e-mail — les mêmes personnes qui feront le check-in.",
      },
      {
        n: "03",
        t: "Demander à réserver",
        d: "Pas de réservation instantanée. Hamza confirme pour qu’Airbnb et ce calendrier ne vendent pas la même nuit deux fois.",
      },
      {
        n: "04",
        t: "Payer sur WhatsApp",
        d: "Après confirmation, Hamza envoie le montant. Pas de carte sur ce site pour l’instant.",
      },
      {
        n: "05",
        t: "Check-in sur votre lien",
        d: "Passeport ou CIN, règlement, signature manuscrite. C’est ainsi qu’un séjour touristique est identifié au Maroc.",
      },
    ],
  },
  rules: {
    eyebrow: "Pour les voyageurs",
    title: "Règles voyageurs et droit marocain",
    disclaimer:
      "Cette page explique comment nous accueillons un court séjour au Maroc. Ce n’est pas un avis d’avocat et cela ne remplace pas le contrat. Le règlement en français que vous signez au check-in est le règlement du logement.",
    houseRulesTitle: "Règlement intérieur (original français)",
    houseRulesLead: "Ce sont les règles que vous signez au check-in.",
    sourcesTitle: "Les textes que nous suivons",
    searchStays: "Chercher un séjour",
    howBooking: "Comment réserver",
    sections: [
      {
        id: "what-you-are-booking",
        title: "Ce que vous réservez",
        body: [
          "Un séjour ici est un court séjour touristique dans un logement meublé — des nuits, pas une année, pas une résidence principale. En droit marocain, cela relève de l’hébergement touristique (loi 80-14), pas du bail d’habitation (loi 67-12).",
          "Les plateformes (Airbnb, Booking, Vrbo ou ce site) ne remplacent pas les devoirs de l’hôte. L’hôte est celui qui confirme le séjour, identifie les voyageurs et remet les clés. Ici, c’est Hamza.",
          "Nous n’utilisons pas la réservation instantanée. Une demande n’est confirmée que si le calendrier est libre ici et sur Airbnb, pour ne pas vendre deux fois le même appartement.",
        ],
      },
      {
        id: "why-id",
        title: "Pourquoi nous demandons votre identité",
        body: [
          "Les hôtes touristiques au Maroc tiennent un registre des voyageurs et déclarent les arrivées aux autorités locales (fiches / formulaires de police). C’est pourquoi le check-in demande un passeport ou une CIN, et une signature, avant que l’arrivée soit complète.",
          "Ce n’est pas un formulaire marketing. C’est ainsi qu’un court séjour sérieux est tenu : qui est dans le logement, pour quelles nuits, sous quel règlement.",
          "Les noms de la réservation doivent correspondre aux personnes qui dorment dans l’appartement. Les voyageurs supplémentaires non annoncés sont refusés.",
        ],
      },
      {
        id: "tax",
        title: "Taxe de séjour",
        body: [
          "Les communes peuvent prélever une taxe de séjour par personne et par nuit sur l’hébergement touristique, y compris les appartements meublés loués à des voyageurs. Le tarif est local — Agadir, Marrakech et Essaouira fixent le leur.",
          "Si une taxe s’applique à votre séjour, Hamza l’indique avec la confirmation, en dirhams. Ce site n’invente pas un montant à votre place.",
          "Airbnb et Booking ne collectent pas toujours la taxe marocaine pour l’hôte. Réserver ici ne la cache pas ; elle reste sur la confirmation que vous recevez vraiment.",
        ],
      },
      {
        id: "house-rules",
        title: "Un règlement qui n’est pas optionnel",
        body: [
          "L’appartement est un logement de courte durée, pas une salle de fête, un plateau de tournage ou un commerce. Rassemblements, shootings commerciaux non déclarés, tabac à l’intérieur et animaux sont refusés — comme l’écrit le règlement français que vous signez.",
          "Les couples marocains non mariés ne sont pas accueillis dans ce logement. C’est une règle de maison, appliquée à la réservation et à la porte, selon la façon dont ce séjour est tenu au Maroc.",
          "Le respect du voisinage fait partie du séjour. Une plainte de l’immeuble peut y mettre fin, sans remboursement des nuits restantes.",
        ],
      },
      {
        id: "cities",
        title: "Agadir, Marrakech, Essaouira",
        body: [
          "Les mêmes devoirs suivent le séjour, pas le logo d’une plateforme : identité, immeuble calme, dates confirmées, paiement convenu sur WhatsApp après confirmation.",
          "Aujourd’hui, le logement ouvert à la réservation est à Agadir. Marrakech et Essaouira sont des villes que nous accueillons — les annonces apparaissent quand un logement est réellement prêt.",
        ],
      },
    ],
    sources: [
      {
        name: "Loi n° 80-14 relative aux établissements touristiques et aux autres formes d’hébergement touristique",
        note: "Dahir n° 1-15-108 du 18 août 2015. Le cadre des hôtels, riads, maisons d’hôtes et locations meublées touristiques.",
      },
      {
        name: "Décret n° 2-23-441",
        note: "Publié en 2023. Règles d’application de l’hébergement touristique, y compris des formes qui restaient dans une zone grise sur les plateformes.",
      },
      {
        name: "Loi n° 47-06, telle que modifiée (notamment par la loi n° 07-20)",
        note: "Fiscalité locale, dont la taxe de séjour fixée par chaque commune.",
      },
      {
        name: "Loi n° 67-12 relative à la location des locaux à usage d’habitation",
        note: "Le bail d’habitation ordinaire. Un séjour de quelques nuits n’est pas ce contrat.",
      },
    ],
  },
  help: {
    eyebrow: "Aide",
    title: "Écrire à l’hôte",
    lead: "Dates, arrivée, check-in, Marrakech ou Essaouira quand un logement n’est pas encore en ligne — un seul WhatsApp, Hamza.",
    whatsapp: "WhatsApp",
    cities: "Hamza · Agadir, Marrakech, Essaouira",
    openWa: "Ouvrir WhatsApp",
    before: "Avant d’écrire",
    bullets: [
      "Faites une demande sur la page du séjour si vous avez besoin de dates à Agadir.",
      "Le check-in est un lien privé après confirmation — pièce d’identité et signature.",
      "Les codes d’accès s’envoient après réservation, ils ne sont pas publiés ici.",
    ],
    openStay: "Ouvrir le séjour d’Agadir →",
    waMessage: "Bonjour Hamza, j’ai une question sur un séjour.",
  },
  auth: {
    eyebrow: "Voyageur",
    logIn: "Connexion",
    wrong: "E-mail ou mot de passe incorrect.",
    email: "E-mail",
    password: "Mot de passe",
    continue: "Continuer",
    newHere: "Nouveau ici ?",
    createAccount: "Créer un compte",
    createTitle: "Créer un compte",
    fullName: "Nom complet",
    phone: "Téléphone / WhatsApp",
    passwordHint: "Mot de passe (8+)",
    haveOne: "Déjà un compte ?",
  },
  account: {
    eyebrow: "Votre séjour",
    hello: (name: string) => `Bonjour, ${name}`,
    requested: "Demande envoyée. Hamza confirmera sur WhatsApp pour que le calendrier Airbnb reste clair.",
    empty: "Aucune demande pour l’instant.",
    seeApartment: "Voir l’appartement",
    line: (nights: number, guests: number, total: number, status: string) =>
      `${nights} nuits · ${guests} voyageurs · ${total} MAD · ${status}`,
    status: {
      pending: "Demandé",
      confirmed: "Confirmé",
      declined: "Refusé",
      cancelled: "Annulé",
    },
    openCheckin: "Ouvrir le check-in",
    logOut: "Déconnexion",
  },
  booking: {
    perNight: "/ nuit",
    seasonal: "Saisonnier · 400–550 MAD. Le ménage est facturé au propriétaire, pas ajouté ici.",
    nights: (n: number) => (n === 1 ? "1 nuit" : `${n} nuits`),
    total: "Total",
    conflict: "Ces nuits chevauchent un séjour déjà au calendrier.",
    unavailable: "Ces dates ne sont pas disponibles.",
    failed: "La demande a échoué.",
    sending: "Envoi…",
    request: "Demander à réserver",
    logInToRequest: "Se connecter pour demander",
    notInstant: "Pas instantané. Hamza confirme pour que ce calendrier et Airbnb ne se croisent jamais. Paiement sur WhatsApp après confirmation — pas de carte sur ce site pour l’instant.",
  },
  card: {
    availableNow: "Disponible maintenant",
    facts: (guests: number, bedrooms: number, beds: number, baths: number) =>
      `${guests} voyageurs · ${bedrooms} chambre · ${beds} lit · ${baths} salles de bain`,
    fromNight: (amount: number) => `À partir de ${amount} MAD / nuit`,
    reviews: (rating: string, n: number) => `★ ${rating} · ${n} avis`,
  },
};

export const AR: typeof EN = {
  dir: "rtl",
  lang: "ar",
  meta: {
    defaultTitle: "GreatImmob — إقامات في أكادير ومراكش والصويرة",
    description:
      "احجز إقامة قصيرة في أكادير أو مراكش أو الصويرة. اطلب التواريخ، يؤكّد المضيف، ثم تسجيل الوصول ببطاقة الهوية. حمزة على الأرض.",
    stays: "الإقامات",
    staysDesc: "إقامات قصيرة في أكادير ومراكش والصويرة. اطلب الحجز مع حمزة.",
    stay: "الشقة",
    how: "كيف يعمل الحجز",
    howDesc: "بحث، طلب حجز، تأكيد المضيف، الدفع عبر واتساب، ثم تسجيل الوصول ببطاقة الهوية.",
    rules: "قواعد الضيوف والقانون المغربي",
    rulesDesc: "كيف نستقبل الإقامة القصيرة في المغرب: القانون 80-14، الهوية، النظام الداخلي، وضريبة الإقامة.",
    help: "مساعدة",
    helpDesc: "واتساب حمزة للمواعيد أو تسجيل الوصول أو إقامة في أكادير أو مراكش أو الصويرة.",
    destination: (city: string) => `إقامات في ${city}`,
    destinationDesc: (city: string, tagline: string) => `إقامات قصيرة في ${city}، المغرب. ${tagline}`,
  },
  nav: {
    stays: "الإقامات",
    destinations: "الوجهات",
    howItWorks: "كيف يعمل الحجز",
    guestRules: "قواعد الضيوف",
    help: "مساعدة",
    logIn: "دخول",
    signUp: "إنشاء حساب",
    menu: "القائمة",
    openMenu: "فتح القائمة",
    closeMenu: "إغلاق القائمة",
    language: "اللغة",
  },
  footer: {
    blurb:
      "إقامات قصيرة في أكادير ومراكش والصويرة. اطلب الحجز، يؤكّد المضيف، ثم تسجيل الوصول — نفس إيقاع Airbnb أو Booking، وحمزة على واتساب.",
    book: "احجز",
    stay: "الإقامة",
    allStays: "كل الإقامات",
    superhost: (host: string) => `${host} · سوبر هوست · المغرب`,
  },
  search: {
    where: "أين",
    checkIn: "الوصول",
    checkout: "المغادرة",
    guests: "الضيوف",
    who: "من",
    addGuests: "أضف ضيوفاً",
    guest1: "ضيف واحد",
    guest2: "ضيفان",
    adults: "بالغون",
    adultsHint: "13 سنة فأكثر",
    children: "أطفال",
    childrenHint: "من 2 إلى 12 سنة",
    pets: "حيوانات أليفة",
    petsHint: "هل تسافر مع حيوان؟",
    petsNotAllowed: "هذه الشقة لا تقبل الحيوانات.",
    maxPeople: "هذه الشقة تتسع لشخصين.",
    peopleSummary: (n: number) => (n === 1 ? "ضيف واحد" : `${n} ضيوف`),
    petsSummary: (n: number) => (n === 1 ? "حيوان واحد" : `${n} حيوانات`),
    search: "بحث",
  },
  city: {
    agadir: {
      name: "أكادير",
      region: "الساحل الأطلسي",
      tagline: "مدينة شاطئية، شمس الشتاء، والطريق إلى تغازوت.",
      blurb:
        "أكادير هي المدينة المفتوحة على هذا الموقع اليوم: شقة يمكنك طلب حجزها، وحمزة على الأرض للمفاتيح وواتساب وتسجيل الوصول.",
      heroAlt: "خليج أكادير والشاطئ، المغرب",
      cardAlt: "شاطئ أكادير وتل أوفلا",
    },
    marrakech: {
      name: "مراكش",
      region: "المدينة القديمة والنخيل",
      tagline: "رياض، أفنية، وليالي المدينة الحمراء.",
      blurb:
        "ستظهر بيوت مراكش هنا عندما تكون جاهزة فعلاً — نفس طلب الحجز، نفس المضيف، بلا إعلانات مخترعة.",
      heroAlt: "ساحة جامع الفنا في مراكش عند الغروب",
      cardAlt: "صومعة الكتبية عند الغروب، مراكش",
    },
    essaouira: {
      name: "الصويرة",
      region: "مدينة أطلسية",
      tagline: "أسوار، ريح، والميناء العامل.",
      blurb:
        "الصويرة على خريطة نفس المجموعة. عندما تكون إقامة جاهزة، ستظهر بجانب أكادير — وليس قبل ذلك.",
      heroAlt: "بيوت بيضاء وزرقاء خلف أسوار الصويرة",
      cardAlt: "قوارب صيد زرقاء في ميناء الصويرة",
    },
  },
  home: {
    citiesLine: "أكادير · مراكش · الصويرة",
    title: "احجز إقامة في المغرب.",
    titleAccent: " مباشرة مع المضيف.",
    lead: "شقق تطلبها كما في Airbnb، ويؤكّدها سوبر هوست، وتسجّل وصولك ببطاقة الهوية — وليست مطوية عن شركة.",
    searchHint: "طلب حجز · حمزة يؤكّد · تسجيل الوصول بجواز أو بطاقة تعريف",
    destinationsEyebrow: "الوجهات",
    destinationsTitle: "أين يمكنك الإقامة",
    homesAvailable: "بيوت متاحة",
    openingSoon: "قريباً",
    availableNow: "متاح الآن",
    placesToBook: "أماكن للحجز",
    allStays: "كل الإقامات",
    howEyebrow: "كيف يعمل الحجز",
    howTitle: "نفس فكرة المنصات الكبيرة. أصغر، وعلى الأرض.",
    fullPath: "مسار الحجز كاملاً ←",
    airbnbRating: "تقييم Airbnb",
    guestReviews: "آراء الضيوف",
    notInstant: "ليس حجزاً فورياً",
    request: "طلب",
    lawEyebrow: "قواعد الضيوف · المغرب",
    lawTitle: "الإقامة القصيرة هنا تخضع لقواعد السياحة المغربية.",
    lawLead:
      "القانون 80-14، الهوية عند تسجيل الوصول، النظام الداخلي بالفرنسية، وضريبة الإقامة إن طبّقتها الجماعة. نفس المعيار الذي يدين به بيت سياحي مصنّف للضيف — وللدولة.",
    readRules: "اقرأ قواعد الضيوف",
    lawPoints: [
      "بضع ليالٍ في بيت مفروش إقامة سياحية، وليست كراء سكنياً.",
      "جواز أو بطاقة تعريف عند تسجيل الوصول — على المضيف أن يعرف من في البيت.",
      "لا حفلات، ولا ضيوف إضافيون غير مصرّح بهم. لا نستقبل الأزواج المغاربة غير المتزوجين.",
    ],
    faqEyebrow: "أسئلة",
    faqTitle: "قبل أن تطلب",
    whatsappTitle: "ليلة ليست على الموقع بعد؟",
    whatsappLead: "التواريخ، المدينة، ضيفان — حمزة يرد على واتساب.",
    messageHamza: "راسل حمزة",
    waMessage: "مرحبا حمزة، أريد حجز إقامة.",
    steps: [
      { n: "01", t: "ابحث عن مدينة", d: "أكادير مفتوحة. مراكش والصويرة تُضافان عندما يكون البيت جاهزاً فعلاً — أبداً بطاقات وهمية." },
      { n: "02", t: "اطلب الحجز", d: "أرسل التواريخ من حسابك. حمزة يؤكّد حتى لا يتقاطع هذا التقويم مع Airbnb." },
      { n: "03", t: "ادفع بعد التأكيد", d: "لا بطاقة على هذا الموقع بعد. المبلغ يصل على واتساب عندما تصبح الإقامة لك." },
      { n: "04", t: "سجّل الوصول", d: "رابط خاص: الهوية، النظام الداخلي، توقيع بخط اليد — الملف الذي تحتاجه إقامة سياحية جدية في المغرب." },
    ],
    faqs: [
      {
        q: "هل هذا حجز فوري؟",
        a: "لا. كل إقامة طلب. هكذا لا يُباع الشقة نفسها على Airbnb وهنا في الليلة ذاتها.",
      },
      {
        q: "لماذا تطلبون الهوية؟",
        a: "الإقامات السياحية في المغرب تحتفظ بسجل للضيوف. تسجيل الوصول هو الملف القانوني، وليس استمارة تسويق.",
      },
      {
        q: "هل يمكنني حجز مراكش أو الصويرة اليوم؟",
        a: "المدينتان على الخريطة. الإعلانات تظهر عندما يكون البيت جاهزاً فعلاً. أكادير هي المدينة التي يمكنك طلبها الآن.",
      },
    ],
  },
  stays: {
    eyebrow: "بحث",
    inCity: (city: string) => `إقامات في ${city}`,
    inMorocco: "إقامات في المغرب",
    lead: "اطلب التواريخ. حمزة يؤكّد. أكادير مفتوحة؛ مراكش والصويرة تنضمان عندما يكون البيت جاهزاً فعلاً.",
    all: "الكل",
    emptyTitle: (city: string) => `لا بيت مفتوح في ${city} بعد`,
    emptyLead: "لا نخترع شققاً. أخبر حمزة بتواريخك — أو احجز إقامة أكادير المفتوحة الآن.",
    seeAgadir: "شاهد أكادير",
    waLooking: (city: string) => `مرحبا حمزة، أبحث عن إقامة في ${city}.`,
  },
  stay: {
    reviews: (n: number) => `${n} تقييمات`,
    hostedBy: (host: string, role: string) => `يستضيفه ${host} · ${role}`,
    facts: (guests: number, bedrooms: number, beds: number, baths: number) =>
      `${guests} ضيوف · ${bedrooms} غرفة · ${beds} سرير · ${baths} حمّام`,
    houseRules: "النظام الداخلي",
    houseRulesLead: "نفس قواعد عقد الإقامة. النص الأصلي بالفرنسية.",
    whyId: "لماذا نطلب الهوية، وقانون الإقامة القصيرة في المغرب",
    alsoListed: "أيضاً على",
    calendars: ". حمزة يؤكّد طلبات .com حتى لا يتقاطع التقويمان.",
    whatsapp: (host: string, phone: string) => `واتساب ${host} · ${phone}`,
    title: "شقة بغرفة واحدة | واي فاي فايبر | هادئة وأنيقة",
    subtitle: "وحدة كاملة · حي المحمدي، أكادير",
    about:
      "شقة هادئة بغرفة نوم واحدة في حي المحمدي بأكادير — نفس البيت الذي يستضيفه حمزة على Airbnb كسوبر هوست. واي فاي فايبر، سرير واحد، حمّام ونصف. ضيفان.",
    badges: ["مفضّل الضيوف", "ضمن أفضل 10٪ من البيوت"],
    amenities: ["واي فاي فايبر", "شقة كاملة", "غرفة واحدة", "سرير واحد", "حمّام ونصف", "عمارة هادئة"],
    headline: "غرفة هادئة في حي المحمدي",
  },
  dest: {
    openingTitle: (city: string) => `بيوت ${city} قيد التجهيز`,
    openingLead: "لا إعلانات مخترعة. عندما تكون إقامة جاهزة ستظهر هنا. أكادير قابلة للحجز اليوم.",
    bookAgadir: "احجز أكادير",
    whatsappHamza: "واتساب حمزة",
    waCity: (city: string) => `مرحبا حمزة، أبحث عن إقامة في ${city}.`,
  },
  how: {
    eyebrow: "الحجز",
    title: "كيف تحجز إقامة",
    lead: (phone: string) =>
      `المسار هو الذي تعرفه من Airbnb أو Booking: بحث، تواريخ، طلب، تأكيد — ثم تسجيل وصول مغربي سليم، مع حمزة على ${phone}.`,
    searchStays: "ابحث عن إقامة",
    guestRules: "قواعد الضيوف",
    steps: [
      {
        n: "01",
        t: "اختر مدينة وتواريخاً",
        d: "ابحث في أكادير أو مراكش أو الصويرة. تظهر البيوت المفتوحة فقط. اليوم هي غرفة حي المحمدي في أكادير.",
      },
      {
        n: "02",
        t: "أنشئ حساب ضيف",
        d: "طلب الحجز يحتاج اسماً وبريداً — نفس الأشخاص الذين سيسجّلون الوصول.",
      },
      {
        n: "03",
        t: "اطلب الحجز",
        d: "ليس حجزاً فورياً. حمزة يؤكّد حتى لا يبيع هذا التقويم وAirbnb الليلة نفسها مرتين.",
      },
      {
        n: "04",
        t: "ادفع على واتساب",
        d: "بعد التأكيد يرسل حمزة المبلغ. لا بطاقة على هذا الموقع بعد.",
      },
      {
        n: "05",
        t: "سجّل الوصول من رابطك",
        d: "جواز أو بطاقة تعريف، النظام الداخلي، توقيع بخط اليد. هكذا تُعرَّف الإقامة السياحية في المغرب.",
      },
    ],
  },
  rules: {
    eyebrow: "للضيوف",
    title: "قواعد الضيوف والقانون المغربي",
    disclaimer:
      "هذه الصفحة تشرح كيف نستقبل الإقامة القصيرة في المغرب. ليست رأياً قانونياً ولا تغني عن العقد. النظام الداخلي بالفرنسية الذي توقّعه عند تسجيل الوصول هو نظام البيت.",
    houseRulesTitle: "النظام الداخلي (الأصل الفرنسي)",
    houseRulesLead: "هذه القواعد التي توقّعها عند تسجيل الوصول.",
    sourcesTitle: "النصوص التي نتبعها",
    searchStays: "ابحث عن إقامة",
    howBooking: "كيف يعمل الحجز",
    sections: [
      {
        id: "what-you-are-booking",
        title: "ماذا تحجز",
        body: [
          "الإقامة هنا إقامة سياحية قصيرة في بيت مفروش — ليالٍ، لا سنة، وليست سكناً رئيسياً. في القانون المغربي هذا يدخل في الإيواء السياحي (القانون 80-14)، لا في كراء السكن (القانون 67-12).",
          "المنصات (Airbnb أو Booking أو Vrbo أو هذا الموقع) لا تعوّض واجبات المضيف. المضيف هو من يؤكّد الإقامة ويعرّف الضيوف ويسلّم المفاتيح. هنا هو حمزة.",
          "لا نستخدم الحجز الفوري. لا يُؤكَّد الطلب إلا إذا كان التقويم حرّاً هنا وعلى Airbnb، حتى لا تُباع الشقة مرتين.",
        ],
      },
      {
        id: "why-id",
        title: "لماذا نطلب هويتك",
        body: [
          "مضيفو السياحة في المغرب يمسكون سجلاً للضيوف ويصرّحون بالمسافرين للسلطات المحلية (استمارات الوصول / فيش الشرطة). لذلك يطلب تسجيل الوصول جواز سفر أو بطاقة تعريف، وتوقيعاً، قبل اكتمال الوصول.",
          "الملف ليس استمارة تسويق. هكذا تُدار إقامة قصيرة جدية: من في البيت، لأي ليالٍ، وأي نظام داخلي.",
          "الأسماء في الحجز يجب أن تطابق من ينام في الشقة. الضيوف الإضافيون غير المعلن عنهم يُرفضون.",
        ],
      },
      {
        id: "tax",
        title: "ضريبة الإقامة",
        body: [
          "يجوز للجماعات فرض ضريبة إقامة (taxe de séjour) عن كل شخص وعن كل ليلة على الإيواء السياحي، بما فيه الشقق المفروشة المؤجرة للمسافرين. السعر محلي — أكادير ومراكش والصويرة يحدّد كل منها سعره.",
          "إن انطبقت ضريبة على إقامتك، يذكرها حمزة مع التأكيد بالدرهم. هذا الموقع لا يخترع رقماً نيابة عنك.",
          "Airbnb وBooking لا يجمعان دائماً الضريبة المغربية للمضيف. الحجز المباشر هنا لا يخفيها؛ تبقى على التأكيد الذي تستلمه فعلاً.",
        ],
      },
      {
        id: "house-rules",
        title: "نظام داخلي ليس اختيارياً",
        body: [
          "الشقة بيت إقامة قصيرة، ليست قاعة حفلات ولا موقع تصوير ولا محلاً. التجمعات والتصوير التجاري غير المصرّح به والتدخين داخل البيت والحيوانات مرفوضة — كما هو مكتوب في النص الفرنسي الذي توقّعه.",
          "لا نستقبل الأزواج المغاربة غير المتزوجين في هذا البيت. هذه قاعدة منزل، تُطبَّق عند الحجز وعند الباب، وفق طريقة إدارة هذه الإقامة في المغرب.",
          "احترام الجيران جزء من الإقامة. شكوى من العمارة يمكن أن تنهي الإقامة دون استرداد الليالي المتبقية.",
        ],
      },
      {
        id: "cities",
        title: "أكادير، مراكش، الصويرة",
        body: [
          "الواجبات نفسها تتبع الإقامة لا شعار المنصة: الهوية، عمارة هادئة، تواريخ مؤكدة، دفع متفق عليه على واتساب بعد التأكيد.",
          "اليوم البيت القابل للحجز في أكادير. مراكش والصويرة مدينتان نستقبل فيهما — الإعلانات تظهر عندما يكون البيت جاهزاً فعلاً.",
        ],
      },
    ],
    sources: [
      {
        name: "القانون رقم 80-14 المتعلق بالمؤسسات السياحية وبأشكال الإيواء السياحي الأخرى",
        note: "الظهير الشريف رقم 1-15-108 بتاريخ 18 أغسطس 2015. إطار الفنادق والرياض وبيوت الضيافة والكراء المفروش السياحي.",
      },
      {
        name: "المرسوم رقم 2-23-441",
        note: "نُشر سنة 2023. قواعد تطبيق الإيواء السياحي، بما فيه أشكال كانت في منطقة رمادية على منصات الحجز.",
      },
      {
        name: "القانون رقم 47-06 كما تم تعديله (ولا سيما بالقانون رقم 07-20)",
        note: "الجبايات المحلية، ومنها ضريبة الإقامة التي تحدّدها كل جماعة.",
      },
      {
        name: "القانون رقم 67-12 المتعلق بكراء المحلات المعدة للسكنى",
        note: "قانون الكراء السكني العادي. إقامة بضع ليالٍ ليست ذلك العقد.",
      },
    ],
  },
  help: {
    eyebrow: "مساعدة",
    title: "راسل المضيف",
    lead: "التواريخ، الوصول، تسجيل الوصول، مراكش أو الصويرة عندما لا يكون البيت على الموقع بعد — واتساب واحد، حمزة.",
    whatsapp: "واتساب",
    cities: "حمزة · أكادير، مراكش، الصويرة",
    openWa: "افتح واتساب",
    before: "قبل أن تكتب",
    bullets: [
      "اطلب الحجز من صفحة الإقامة إن كنت تحتاج تواريخ أكادير.",
      "تسجيل الوصول رابط خاص بعد التأكيد — هوية وتوقيع.",
      "رموز الباب تُرسل بعد الحجز، ولا تُنشر هنا.",
    ],
    openStay: "افتح إقامة أكادير ←",
    waMessage: "مرحبا حمزة، لدي سؤال عن إقامة.",
  },
  auth: {
    eyebrow: "ضيف",
    logIn: "دخول",
    wrong: "البريد أو كلمة السر غير صحيحة.",
    email: "البريد الإلكتروني",
    password: "كلمة السر",
    continue: "متابعة",
    newHere: "جديد هنا؟",
    createAccount: "أنشئ حساباً",
    createTitle: "إنشاء حساب",
    fullName: "الاسم الكامل",
    phone: "الهاتف / واتساب",
    passwordHint: "كلمة السر (8+)",
    haveOne: "لديك حساب؟",
  },
  account: {
    eyebrow: "إقامتك",
    hello: (name: string) => `مرحباً، ${name}`,
    requested: "تم إرسال الطلب. سيؤكّد حمزة على واتساب حتى يبقى تقويم Airbnb واضحاً.",
    empty: "لا طلبات بعد.",
    seeApartment: "شاهد الشقة",
    line: (nights: number, guests: number, total: number, status: string) =>
      `${nights} ليالٍ · ${guests} ضيوف · ${total} درهم · ${status}`,
    status: {
      pending: "مطلوب",
      confirmed: "مؤكّد",
      declined: "مرفوض",
      cancelled: "ملغى",
    },
    openCheckin: "افتح تسجيل الوصول",
    logOut: "خروج",
  },
  booking: {
    perNight: "/ الليلة",
    seasonal: "موسمي · 400–550 درهم. التنظيف يُفوتر للمالك، ولا يُضاف هنا.",
    nights: (n: number) => (n === 1 ? "ليلة واحدة" : `${n} ليالٍ`),
    total: "المجموع",
    conflict: "هذه الليالي تتقاطع مع إقامة موجودة في التقويم.",
    unavailable: "هذه التواريخ غير متاحة.",
    failed: "فشل الطلب.",
    sending: "جارٍ الإرسال…",
    request: "اطلب الحجز",
    logInToRequest: "سجّل الدخول للطلب",
    notInstant: "ليس فورياً. حمزة يؤكّد حتى لا يتقاطع هذا التقويم مع Airbnb. الدفع على واتساب بعد التأكيد — لا بطاقة على هذا الموقع بعد.",
  },
  card: {
    availableNow: "متاح الآن",
    facts: (guests: number, bedrooms: number, beds: number, baths: number) =>
      `${guests} ضيوف · ${bedrooms} غرفة · ${beds} سرير · ${baths} حمّام`,
    fromNight: (amount: number) => `من ${amount} درهم / الليلة`,
    reviews: (rating: string, n: number) => `★ ${rating} · ${n} تقييمات`,
  },
};

const ALL = { en: EN, fr: FR, ar: AR } as const;

export type SiteCopy = typeof EN;

export function siteCopy(locale: SiteLocale): SiteCopy {
  return ALL[locale] ?? EN;
}

export type CitySlug = keyof SiteCopy["city"];
